trigger:
  - master

variables:
  RESOURCE_GROUP: splineintegrtest
  COSMOSDB_NAME_PREFIX: splineintegrtest
  GIT_BRANCH: release/0.3

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- task: AzureCLI@1
  displayName: Create Azure resources
  inputs:
    azureSubscription: ARMConnection
    scriptPath: before-build.sh

- task: Maven@3
  displayName: Build Spline
  inputs:
    mavenPomFile: 'spline/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    #Maven command line arguments:
    # -P: profile
    # -DskipTests: build only, do not run tests
    # -B: batch mode, reduce output verbosity
    goals: package -Pspark-2.4 -DskipTests -B

- task: Maven@3
  displayName: Run Spline tests
  inputs:
    mavenPomFile: 'spline/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    #Maven command line arguments:
    # -P: profile
    # -D: set connection string for Cosmos DB instance
    goals: test -Pspark-2.4 -Dtest.spline.mongodb.url=$(COSMOSDB_CONN_STRING)

- task: CopyFiles@2
  displayName: Copy web app to artifacts directory
  inputs:
    sourceFolder: 'spline/web/target'
    contents: |
      *.jar
      *.war
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish web app artifacts
  inputs:
    artifactName: 'spline'

- task: AzureCLI@1
  displayName: Delete Azure resources
  condition: always()
  inputs:
    azureSubscription: ARMConnection
    scriptPath: after-build.sh

